pull_request_rules:
  - name: Automatic approve on dependabot PR
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE

  - name: Automatic merge on approval
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=test
      - check-success=version
      - check-success=plantuml
      - check-success=gem
      - check-success=publish-dev
      - check-success=shellcheck
    actions:
      merge:
        method: merge
        strict: smart

  - name: Thank contributor
    conditions:
      - merged
    actions:
      comment:
        message: "Thank you @{{author}} for your contribution!"
