name: amend

on:
  issue_comment:
    types: [created]

jobs:
  amend:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/amend')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: amend
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: .github/scripts/amend.sh --user payex-dev --verbose
