name: No Java

on:
  push:
    tags:
    - '*'
  pull_request:

jobs:
  test:
    name: No Java
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.2-alpine3.12

    steps:
    - uses: actions/checkout@v2

    - name: Bundle install
      run: |
        find .
        bundle install --jobs 4 --retry 3

    - name: Test with Rake
      run: bundle exec rspec --tag no_java
