name: No Java

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.0-alpine3.11

    steps:
    - uses: actions/checkout@v2

    - name: Bundle install
      run: bundle install

    - name: Test with Rake
      run: NO_JAVA=1 bundle exec rake
