name: No Java

on:
  push:
    tags:
    - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.2

    steps:
    - uses: actions/checkout@v4

    - name: Bundle install
      run: bundle install --jobs 4 --retry 3

    - name: RSpec
      run: bundle exec rspec --tag no_java
