name: No PlantUML

on:
  push:
    tags:
    - '*'
  pull_request:

jobs:
  test:
    name: No PlantUML
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x

    - name: Bundle install
      run: bundle install --jobs 4 --retry 3

    - name: Test with Rake
      run: bundle exec rspec --tag no_plantuml
