name: No PlantUML

on:
  push:
    tags:
    - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Test with Rake
      run: bundle exec rspec --tag no_plantuml
