name: No Java

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.0-alpine3.11

    steps:
    - uses: actions/checkout@v2
    - run: docker exec -it <container_id_or_name> echo "I'm inside the container!"

    - name: Bundle install
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Remove plantuml.1.2020.5.jar
      run:  rm bin/plantuml.1.2020.5.jar

    - name: Test with Rake
      run: NO_PLANTUML=1 bundle exec rake
