name: Shell

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: ShellCheck
        uses: bewuethr/shellcheck-action@v2
